# Generated by Django 5.1.2 on 2024-12-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_plate', models.CharField(max_length=15, unique=True)),
                ('model', models.CharField(max_length=50)),
                ('driver_name', models.CharField(max_length=100)),
                ('available', models.IntegerField()),
            ],
        ),
    ]
