# Generated by Django 5.1.2 on 2025-01-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=100)),
                ('seating_capacity', models.IntegerField()),
                ('rate_per_day', models.DecimalField(decimal_places=2, max_digits=8)),
                ('allowed_km_per_day', models.IntegerField()),
                ('cost_per_extra_km', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
