# Generated by Django 5.1.5 on 2025-01-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='confirmation_code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
