# Generated by Django 5.1.6 on 2025-02-21 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Full_name',
            new_name='full_name',
        ),
    ]
