# Generated by Django 5.1.6 on 2025-02-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_full_name_contact_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cab',
            name='seats',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
